//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoilerController.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BoilerController.Resource.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler Over Heated!!!.
        /// </summary>
        internal static string BoilerException {
            get {
                return ResourceManager.GetString("BoilerException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press the Escape to Stop the Operation, Press E to throw error or any key to continue:.
        /// </summary>
        internal static string ContinueInTimer {
            get {
                return ResourceManager.GetString("ContinueInTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any to continue.
        /// </summary>
        internal static string ContinueString {
            get {
                return ResourceManager.GetString("ContinueString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interlock switch is closed!!!.
        /// </summary>
        internal static string InterLockClosed {
            get {
                return ResourceManager.GetString("InterLockClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InterLock is Open State!!! - Please close it to start the operation.
        /// </summary>
        internal static string InterLockOpen {
            get {
                return ResourceManager.GetString("InterLockOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler is in Lockout State.
        /// </summary>
        internal static string Lockout {
            get {
                return ResourceManager.GetString("Lockout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Boiler State is Operational.
        /// </summary>
        internal static string Operational {
            get {
                return ResourceManager.GetString("Operational", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boiler is in Ready State.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Lock is Closed.
        /// </summary>
        internal static string ResetLockClosed {
            get {
                return ResourceManager.GetString("ResetLockClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Lock is Open - Please close the reset lock.
        /// </summary>
        internal static string ResetLockOpen {
            get {
                return ResourceManager.GetString("ResetLockOpen", resourceCulture);
            }
        }
    }
}
